### PR TITLE
Update Gradle

### PR DESCRIPTION
**Pull request by jancborchardt**
Android Studio was bugging me about it being out of date.

Please review @postapczuk @Poussinou  :)

### CODE REVIEW

**Review by postapczuk — COMMENTED** [review]
In fact there is gradle 5 now :)

https://gradle.org/whats-new/gradle-5/

**Comment by jancborchardt** [comment]
Should we update to that then? :) I only did what Android Studio was telling me.

**Comment by postapczuk** [comment]
I think if we are increasing the version, we should do it to the newest one :)

**Comment by jancborchardt** [comment]
Hmm, I’m following the update guide in the blog post but already encounter an error at the first and second steps:
```
~/Light-Android-Launcher$ gradle wrapper --gradle-version=4.10.2
and also
~/Light-Android-Launcher$ gradle help --scan
```

This is the error:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.gradle.internal.reflect.JavaMethod (file:/usr/share/gradle/lib/gradle-base-services-3.4.1.jar) to method java.lang.ClassLoader.getPackages()
WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

FAILURE: Build failed with an exception.

* Where:
Build file '/home/jan/Light-Android-Launcher/build.gradle' line: 12

* What went wrong:
A problem occurred evaluating root project 'Light-Android-Launcher'.
> Could not find method google() for arguments [] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

@postapczuk do you know how to resolve that?

**Comment by postapczuk** [comment]
Ok it looks like android plugin has different numeration tham gradle itself: https://developer.android.com/studio/releases/gradle-plugin#revisions

Merging it.

**Comment by postapczuk** [comment]
To generate gradle wrapper you just need to use `gradle wrapper` command in root, and then just `./gradlew ...`  command

**Comment by postapczuk** [comment]
I will check that soon as possible

**Comment by jancborchardt** [comment]
@postapczuk I fixed the conflict with master. Not sure how to upgrade to latest Gradle as said. But maybe let’s merge this as is to get rid of the annoying popup notification in Android Studio first, and do the next update separately? :)

**Comment by jancborchardt** [comment]
@postapczuk this seems good to merge as a first step, what do you think? :)

**Review by postapczuk — APPROVED** [review]

**Pull request merged**
