### PR TITLE
Update listview selector to be transparent

### PR DESCRIPTION
**Pull request by compost-em-all**
This change helps to clean up the UI of the launcher some by removing the default orange styling on the Listview. This should satify #42 as well as #31 which looks to be a similar Issue. I was working to try and get an underline effect for the OnClick and OnLongPress handlers but without XML it was pretty hacky.

### CODE REVIEW

**Comment by jancborchardt** [comment]
@taylor-josh I don’t have my setup running at the moment, could you add screenshots? :) And thanks a lot for the contribution!

**Comment by compost-em-all** [comment]
I sure can.
I'll make make a quick gif of it when I get home from the gym.

**Review by postapczuk — COMMENTED** [review]
so now when someone will press button will not see what is pressed? I don't think it's good idea...

**Comment by jancborchardt** [comment]
Yeah, agree with @postapczuk – there should be some sort of feedback. Either the underline as in the mockup at https://github.com/light-launcher/Light-Android-Launcher/issues/42, or maybe it’s possible to simply change the color from orange to white?

**Comment by compost-em-all** [comment]
Fair enough. I'm brand new to Android/Java so was learning as I go what I
was able to do.

I'll take another stab at this Issue and submit another PR when I've got it
in a good spot. It'll give me a chance to learn more about Android and app
styling.

Thank you for the feedback.

**Comment by jancborchardt** [comment]
@taylor-josh no worries, we’re all pretty new to it so we’re learning as we go along! :)

**Comment by postapczuk** [comment]
taylor, you don't need to make new Pull Request, just commit and push to the current :)

**Comment by compost-em-all** [comment]
Maybe something more like this?

example

I'm not super thrilled with the way it looks on long press however..

**Comment by jancborchardt** [comment]
Looks nice! Just 2 details:
- In the gif, the entry vanishes for a split-second when tapped, that is the row goes black. Is that just in the animation?
- Could the underline be a bit lower below the text? Similar to in the mockup at https://github.com/light-launcher/Light-Android-Launcher/issues/42 – right now it’s a bit too close stuck to the text.


Also what do you think @postapczuk?

**Comment by compost-em-all** [comment]
Thanks !

As far as I understand, the split second change to black there has
something to do with the entries in the listview getting focus. I tried a
few different ideas to try and disable that but I couldn't figure it out
last night.

I'll take a look at moving the underlining down a smidge tonight if I have
time and see if I can also figure out the changing to black.

**Comment by compost-em-all** [comment]
Had a chance to work on this some more and wanted to present what I came up with.

longpressunderline

I could not find any way to move the underline effect further down away from the text without having to create a style XML file. I am creating the underline by setting a new background with a rectangle where the bottom border is white and then removing it. I could figure out any way where I could programatically create the underline but also have it so far down from the text.

The only thing that I was not able to do was get the underline effect on the favoruites screen when long pressing to remove an app. One other thing to note was that pressing the "add favourite" item underlines it with white vs the gray color - was not sure how we'd want to handle that.

**Comment by postapczuk** [comment]
In my opinion the underline effect is not enough noticable to user, as it is under the thumb... Could you just try to change the color of the highlight instead of underline?

**Comment by compost-em-all** [comment]
Yeah, that's fine. What color are we thinking?

I actually kind of like the underline now that I see it first hand. Being
that I moved the coloring out to the XML files, that would make it easier
to make the coloring themeable in the future if we wanted to (don't have to
though).

Maybe we could do the coloring on highlight and the underline?

**Comment by postapczuk** [comment]
@taylor-josh I think we could have both highlight and underline. I think the highlight should be "almost white" and underline could be the system main default color

**Comment by jancborchardt** [comment]
We don't need both underline and highlight. :) Good point with underline not being so visible – let's just go with highlight.

How about we use a dark grey, inbetween the background black and text white. So that it works with the new slightly visible background, it should probably be something like rgba(50, 50, 50, .5)

**Comment by jancborchardt** [comment]
Here’s a mockup of how it would look like with a full-row background of `rgba(255, 255, 255, .04)` – that is, white with just 4% opacity:
Light Launcher select

I’d say that looks pretty cool and simple, while being very visible no matter where your thumb is.

What do you think @postapczuk @taylor-josh?

**Comment by compost-em-all** [comment]
@jancborchardt yeah, I like that. i'll get something together for this. i'll need to see how I can color the whole row since the padding seems to stop it

**Comment by compost-em-all** [comment]
Don't have anything checked in yet but was able to figure it out.
Will need to clean up what I wrote as I was working through some ideas pretty quickly

example2

**Comment by jancborchardt** [comment]
That looks perfect @taylor-josh! Can't wait to test :)

**Comment by compost-em-all** [comment]
going to close this PR and open a new one.
I made a branch for my pr instead of trying to work out of a fork.

**Comment by postapczuk** [comment]
Beautiful :) Can't wait to merge it :D

**Pull request closed without merging**
