### PR TITLE
Solves #35, #39 and #51

### PR DESCRIPTION
**Pull request by postapczuk**
You can test it with apk: https://www.dropbox.com/s/soqd0b0opc2m2xu/LaLauncher-debug.apk?dl=0
Also issue with not working swipe animations on older devices no longer appear.
Also issue with accidental long press on does not appear.

From Favs to All: swipe to top at the bottom 1/5 of the bottom of screen
From All to Favs: swipe to bottom at 1/2 of the screen (swipe must finish before 1/2 from the top of the screen)

### CODE REVIEW

**Comment by postapczuk** [comment]
Also issue with accidental long press on all apps no longer exist.

**Comment by postapczuk** [comment]
Here is demo gif: https://github.com/postapczuk/Light-Android-Launcher/blob/master/README.md

@jancborchardt

**Comment by jancborchardt** [comment]
Very nice! Just 3 things:
- The requirement of finishing before 1/2 from top of the screen is a bit confusing, especially when you have a smaller phone screen or just swipe further sometimes. It causes it to not eork then. Could we adjust that?
- The animation to open the apps list is a bit slow, can we double the speed?
- The darkened background looks pretty nice! Can we also make it show in the top status bar and bottom controls bar, which are currently black still?

**Comment by jancborchardt** [comment]
Oh and also, the popup informimg about the swipe direction could be in Android Material style, just like we changed the app picker?

**Comment by jancborchardt** [comment]
Oh and another thing: The swipe back from all to favs requires you to use a completely different sensitive area right now, which is also confusing _and_ you have to move your finger up to the top to reach it.

How about: When you are at the top of the list and scroll any further up, the list will go back down going back to the favs screen.

**Comment by postapczuk-inspeerity** [comment]
@jancborchardt 
>The requirement of finishing before 1/2 from top of the screen is a bit confusing, especially when you have a smaller phone screen or just swipe further sometimes. It causes it to not work then. Could we adjust that?
- It was set as I had to specify limit because if I'd set this to the whole screen user will experience slow scrolling (View won't scroll fast while you leave your thumb from screen)
>How about: When you are at the top of the list and scroll any further up, the list will go back down going back to the favs screen.
- Then you'll need to use your thongue twice, and after the first one if you are at the bottom of the list you need to wait a while - is it better? I'm using it for the 3'rd day and seems to me very natural to swipe from top
>The animation to open the apps list is a bit slow, can we double the speed?
- It loads slowly only for the first time (when it loads the app list) - speed is set to 400ms and to 250ms for each swipe. Faster looked for me strange, but I will generate apk for you to check which is better
>The darkened background looks pretty nice! Can we also make it show in the top status bar and bottom controls bar, which are currently black still?
- Yeah I thought about that - I will try
>Oh and also, the popup informimg about the swipe direction could be in Android Material style, just like we changed the app picker?
- Ok.

**Comment by jancborchardt** [comment]
> > The requirement of finishing before 1/2 from top of the screen is a bit confusing, especially when you have a smaller phone screen or just swipe further sometimes. It causes it to not work then. Could we adjust that?
> 
> It was set as I had to specify limit because if I'd set this to the whole screen user will experience slow scrolling (View won't scroll fast while you leave your thumb from screen)

Right. Maybe that’s ok also.


> > How about: When you are at the top of the list and scroll any further up, the list will go back down going back to the favs screen.
> 
> Then you'll need to use your thongue twice, and after the first one if you are at the bottom of the list you need to wait a while - is it better? I'm using it for the 3'rd day and seems to me very natural to swipe from top

I’d say both should be possible. Other apps do this similarly with being able to scroll down to remove the pane again, like Netflix, VLC or reddit.

Similarly with the swiping: For going into all apps, you swipe on the bottom. But for going out, you need to move your thumb to the top. Reaching the top of the phone is not very ergonomic and hard to reach for lots of people. As the swiping should be symmetric, at least the sensitive part should also be on the bottom again. Would that work?



> > The animation to open the apps list is a bit slow, can we double the speed?
> 
> It loads slowly only for the first time (when it loads the app list) - speed is set to 400ms and to 250ms for each swipe. Faster looked for me strange, but I will generate apk for you to check which is better

Ah ok, I see it now. 250ms seems ok. 2 additional things:
- When using the back button, the animation seems slower? Should be the same speed
- When using the home button to go back from all apps to favs, there’s no animation at all. Is it possible to have the same one?


> > The darkened background looks pretty nice! Can we also make it show in the top status bar and bottom controls bar, which are currently black still?
> 
> Yeah I thought about that - I will try


Cool stuff! At least making the top status bar transparent should work, as we do that in the "All apps" view already. :)


> > Oh and also, the popup informimg about the swipe direction could be in Android Material style, just like we changed the app picker?
> 
>  Ok.

:tada:

**Comment by postapczuk** [comment]
applied all suggestions except animation on home screen, as I don't know how to handle it. Both Slide and back press use the same method so animation have same duration, but probably back button fires with some lag.

**Comment by postapczuk** [comment]
@jancborchardt could you set the accepted review And merge?

**Comment by jancborchardt** [comment]
Give me a few minutes to test it :)

**Comment by jancborchardt** [comment]
Btw @postapczuk you don’t need to fork it, just work on a branch of this repository. :) That makes collaboration much easier.

**Comment by postapczuk** [comment]
Ok, next time, I'll do it this way. So how's your testing?

**Comment by jancborchardt** [comment]
Heh, actually cloning takes a bit longer because of the big gifs in the history now :wink:

**Comment by postapczuk** [comment]
Agh Yes, the one was terribly big. In fact you can still download the latest APK from dropbox link in first comment.

**Comment by jancborchardt** [comment]
It’s now already at 35 MB and still loading (am at a Hackweek atm and slow connection due to everyone using the wifi).

I would really suggest to heavily compress the gif (it’s 8 MB now) and to squash the commits with the gif. Otherwise any new contributor will need a long time to clone the repository.

**Comment by postapczuk** [comment]
The problem is with one commit with the 25MB gif. I'll remove this one from history.

**Comment by postapczuk** [comment]
ok, history changed. @jancborchardt please check it in a free time. Thank you and enjoy Hackweek :)

**Review by jancborchardt — APPROVED** [review]
Very nice, works super well now! :+1:

**Comment by jancborchardt** [comment]
Took me some more time even because I had to update Android Studio but I managed – looks and works very nice now! :) Awesome job @postapczuk! :tada:

**Pull request merged**
