### PR TITLE
Change empty favorites text to be more helpful and point to long-press

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @postapczuk :) This makes it way easier to understand how to start out with the app on first run:
New placeholder text "long-press to pick app"

### CODE REVIEW

**Comment by postapczuk** [comment]
@jancborchardt Nice, could you increase version number to 3 and description `1.2` in file: https://github.com/postapczuk/Light-Android-Launcher/blob/master/LaLauncher/build.gradle ? It will trigger the update on the f-droid repo after merge. Hopefuly it will be there in some days/weeks

**Comment by jancborchardt** [comment]
@postapczuk done, thanks for the pointer! :) (I’m a designer and entirely new to Android development.)

In general I’m interested what your plans for this app are, as I have some feedback and issues. This repository does not have the issues activated so there’s no way to open them and discuss. :)

Some examples:
- Currently swipe only works _on_ the text entries, not on the black space above or below.
- Swipe is "indirect", meaning it does not directly swipe the view, it just triggers an animation. Would be much nicer and faster if it’s direct.
- Swiping back often triggers accidental long-press, which takes you out of the flow.
- We could prepopulate some entries like messaging app, phone and clock just to have a better first run experience. Just like Light Phone II does.
- The system bars could be dimmed for even better focus: https://developer.android.com/training/system-ui/dim – I’m trying to look into this.

Then even some advanced stuff:
- The AllAppsActivity could be sorted by frequency of use, if we get that data somewhere.
- We could have a shortcut on top of the AllAppsActivity to enable greyscale mode on the phone, if it supports it: https://lifehacker.com/change-your-screen-to-grayscale-to-combat-phone-addicti-1795821843
- If we want to, there could be 1 single input line up top to define your current focus. Like a to-do, but only one single thing to focus on.
- Generally the question is which API level we want to support as currently the look of the app is simple, but as soon as the app list shows you see the outdated-ness of it – and it’s very bright, compared to the launcher itself. Supporting Android 1.* seems a bit much, and Android Studio for example says "By targeting API 15 [Android 4.0.3] or later, your app will approximately run on 100% of devices". Also see https://en.wikipedia.org/wiki/Android_version_history

What do you generally think? If you open the issues for the repository, I can open them individually. :)

**Comment by postapczuk** [comment]
I am JVM stack developer (Java, Kotlin, Groovy) and this app is also my first for Android, so I'm just learning on it.

Also I'm using this app as my daily launcher so I'm aware of some difficulties of using this app :) 
>     * Currently swipe only works _on_ the text entries, not on the black space above or below.
Yeah this could be done better. In fact for my usage I didn't need that, and had no time to do it lately.

>     * Swipe is "indirect", meaning it does not directly swipe the view, it just triggers an animation. Would be much nicer and faster if it’s direct.
What do you mean "indirect"?

>     * Swiping back often triggers accidental long-press, which takes you out of the flow.
Yep it needs to be "re-thinked" - for now I have no idea how to separate both actions. Maybe long press delay??

>     * We could prepopulate some entries like messaging app, phone and clock just to have a better first run experience. Just like Light Phone II does.
It was in the first version, but alot of users asked to change it. You think about this app as smartphone one as I did, but some older Androids and tablets have different names of actions to run the Contacts and Messaging. My Idea was to keep it simply stupid and work for wide versions of Android, so it is harder to maintain.

>     * The system bars could be dimmed for even better focus: https://developer.android.com/training/system-ui/dim – I’m trying to look into this.
As far as I know this feature is available in later versions of Android

>     * The AllAppsActivity could be sorted by frequency of use, if we get that data somewhere.
A lot of people wrote on Reddit that they hate this feature in launchers. I think it is good idea to give them choice to use that feature :)

>     * We could have a shortcut on top of the AllAppsActivity to enable greyscale mode on the phone, if it supports it: https://lifehacker.com/change-your-screen-to-grayscale-to-combat-phone-addicti-1795821843
Nice idea :)

>     * If we want to, there could be 1 single input line up top to define your current focus. Like a to-do, but only one single thing to focus on.

>     * Generally the question is which API level we want to support as currently the look of the app is simple, but as soon as the app list shows you see the outdated-ness of it – and it’s very bright, compared to the launcher itself. Supporting Android 1.* seems a bit much, and Android Studio for example says "By targeting API 15 [Android 4.0.3] or later, your app will approximately run on 100% of devices". Also see https://en.wikipedia.org/wiki/Android_version_history
I believe that this statistic is not real and takes into consideration only phones with Google Play Services. I was really shocked how many people in India use the oldest androids in their phones. In fact I'm considering to make a fork which will have support only for versions > 4

I've opened the "issues view". It would be great if you create tasks for this issues :)

**Comment by jancborchardt** [comment]
@postapczuk so cool, we can learn together if you like! I’m doing design normally, also for Android apps, but this simpler app is the first time I felt comfortable installing Android Studio and dabbling myself.

Will open issues for the individual points later or tomorrow (busy at the moment). Thanks for your replies already, good points! :)

(I guess this pull request is then ready to be merged, or is anything left?)

**Comment by postapczuk** [comment]
Yep, branch is ready to be merged, but for the future: do not push changes with force. You could just make another commit with description: "new version".

Git is just a version control system - it holds the history of changes, it is not common to "amend" commit and push it with a force flag. The most usual and the best way is just to create a new commit on the same branch. It will be in the same pull request, and Reviewer will be informed.

**Comment by jancborchardt** [comment]
> but for the future: do not push changes with force. You could just make another commit with description: "new version".

Cool, will do it like that in the future. Some projects have different rules, like keeping the amount of commits low.

**Comment by jancborchardt** [comment]
@postapczuk opened issues for all of the things brought up, and also opened a bunch of pull requests to start fixing. :)

Maybe we should start an organization for the launcher, so that we get more people working on it? Maybe even @Collinux of the original Minimalist Launcher wants to join?

**Comment by jancborchardt** [comment]
I now created the organization https://github.com/lightlaunch which we could use to collaborate, and invited you both. :)

(Also contacted Github support if @lightlauncher would be available for use since it seems inactive.)

**Comment by Collinux** [comment]
Hey everybody, glad to see a community picking up the project's philosophies and experimenting with user experience design from a first-principles perspective. I would be glad to join your organization and  advise when it's asked of me, though I'm not interested in directly writing code for Android app development.

Some thoughts as this project is further developed...

>     * Currently swipe only works _on_ the text entries, not on the black space above or below. 
>     * Swipe is "indirect", meaning it does not directly swipe the view, it just triggers an animation. Would be much nicer and faster if it’s direct.
>     * Swiping back often triggers accidental long-press, which takes you out of the flow.
Swiping has a high rate of accidental interaction with the wrong UI elemented at the wrong time. What functionality does a single press and a long press not have that leads you to a need for a third option?

>     * We could prepopulate some entries like messaging app, phone and clock just to have a better first run experience. Just like Light Phone II does.
This can quickly get out of hand and more details don't make a more productive experience. 

>     * The system bars could be dimmed for even better focus: https://developer.android.com/training/system-ui/dim – I’m trying to look into this.
Cool, sounds good.

> Then even some advanced stuff:
> 
>     * The AllAppsActivity could be sorted by frequency of use, if we get that data somewhere.
Frequency of use is not an indicator of what the user wants and it can lead to mindless apps making their way to the top. Also by collecting that data you're storing details on user habits. I agree that there needs to be some custom sorting, though that adds complexity with other menus and options. 

>     * We could have a shortcut on top of the AllAppsActivity to enable greyscale mode on the phone, if it supports it: https://lifehacker.com/change-your-screen-to-grayscale-to-combat-phone-addicti-1795821843
This is more of a Quick Settings feature or system accessibility feature, though it would be an interesting way to create the whole minimalist experience.

>     * If we want to, there could be 1 single input line up top to define your current focus. Like a to-do, but only one single thing to focus on.
Not sure if I understand this correctly... are you trying to allow the control of focus from a keyboard or other input device?
 
>     * Generally the question is which API level we want to support as currently the look of the app is simple, but as soon as the app list shows you see the outdated-ness of it – and it’s very bright, compared to the launcher itself. Supporting Android 1.* seems a bit much, and Android Studio for example says "By targeting API 15 [Android 4.0.3] or later, your app will approximately run on 100% of devices". Also see https://en.wikipedia.org/wiki/Android_version_history
I agree, supporting Android 1 is a bit extreme. My intention here was to minimize the potential for bugs and reduce the app size.

**Comment by jancborchardt** [comment]
@Collinux cool! :) I opened issues for all of these points so we can also discuss in there: https://github.com/postapczuk/Light-Android-Launcher/issues

**Pull request merged**
